version: '3'
services:
  #  # 服务端
  #  citicup-server:
  #    image: citicup/server
  #    build:
  #      context: ./docker
  #      dockerfile: Dockerfile
  #      args:
  #        - ARTIFACT_NAME=citicup-server
  #        - EXPOSED_PORT=8080
#      environment:
#        - VIRTUAL_HOST=citicup.top
#        - VIRTUAL_PORT=8080
#        - LETSENCRYPT_HOST=citicup.top
#        - LETSENCRYPT_EMAIL=1071956678@qq.com
  #    networks:
  #      - citicup
  #      - proxy
  citicup-frontend:
    image: citicup/citicup-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARTIFACT_NAME=citicup-frontend
        - EXPOSED_PORT=8000
    environment:
      - VIRTUAL_HOST=citicup.top
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=citicup.top
      - LETSENCRYPT_EMAIL=1071956678@qq.com
    networks:
      - citicup
      - proxy
    ports:
      - "8081:8000"

networks:
  citicup:
    driver: bridge
  proxy:
    external: true
