version: "2"
services:
  #网关 spring cloud
  api-gateway:
    restart: always
    image: citicup/citicup-api-gateway
    container_name: citicup-api-gateway
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8080","-timeout=60s","--","java","-jar","/app.jar"]
    build:
      context: .
      dockerfile: Dockerfile-api-gateway
      args:
        - ARTIFACT_NAME=citicup-api-gateway-0.0.1-SNAPSHOT
    networks:
      - citicup
      - proxy
    environment:
      - VIRTUAL_HOST=citicup.top
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=citicup.top
      - LETSENCRYPT_EMAIL=1071956678@qq.com
  # eureka
  discovery-server:
    restart: always
    image: citicup/citicup-discovery-server
    container_name: citicup-server
    build:
      context: .
      dockerfile: Dockerfile-api-gateway
      args:
        - ARTIFACT_NAME=citicup-discovery-server-0.0.1-SNAPSHOT
    networks:
      - citicup
  # 内网mysql
  citicup-mysql:
    image: 'mysql:5.7.21'
    container_name: citicup-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=citicup
    volumes: # 设置映射目录
      - ./mysqldb/data:/data/db
      - ./mysqldb/backup:/data/backup
    networks:
      - citicup
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  # 前端站点
  citicup-frontend:
    image: citicup/citicup-frontend
    container_name: citicup-frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARTIFACT_NAME=citicup-frontend
        - EXPOSED_PORT=8000
    entrypoint: ["./dockerize","-wait=tcp://citicup-mysql:3306","-timeout=60s","--","./citicup-app","-profile","prod"]
    networks:
      - citicup

  citicup-admin:
    image: citicup/citicup-admin
    container_name: citicup-admin
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARTIFACT_NAME=citicup-admin
        - EXPOSED_PORT=8080
    entrypoint: ["./dockerize","-wait=tcp://citicup-mysql:3306","-timeout=60s","--","./citicup-app","-profile","prod"]
    networks:
      - citicup

  citicup-plus:
    image: citicup/citicup-plus
    container_name: citicup-plus
    restart: always
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8080","-timeout=60s","--","java","-jar","/app.jar"]
    build:
        context: .
        dockerfile: Dockerfile-api-gateway
        args:
          - ARTIFACT_NAME=citicup-plus-0.0.1-SNAPSHOT
    networks:
      - citicup


  citicup-model:
    image: citicup/citicup-model
    container_name: citicup-model
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-model
    networks:
      - citicup


networks:
  citicup:
    driver: bridge
  proxy:
    external: true
