version: '3'
services:
  #网关 spring cloud
  api-gateway:
    restart: always
    image: citicup/citicup-api-gateway
    container_name: citicup-api-gateway
    entrypoint: ["java","-jar","/app.jar"]
    build:
      context: .
      dockerfile: Dockerfile-api-gateway
      args:
        - ARTIFACT_NAME=citicup-api-gateway-0.0.1-SNAPSHOT
        - EXPOSED_PORT=8082
    networks:
      - citicup
      - proxy
    environment:
      - VIRTUAL_HOST=106.14.140.93
      - VIRTUAL_PORT=8082
      - LETSENCRYPT_HOST=106.14.140.93
      - LETSENCRYPT_EMAIL=1071956678@qq.com
  # 内网mysql
  citicup-mysql:
    image: 'mysql:5.7.21'
    container_name: citicup-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=citicup
    volumes: # 设置映射目录
      - ./mysqldb/data:/data/db
      - ./mysqldb/backup:/data/backup
    networks:
      - citicup
  # 前端站点
  citicup-frontend:
    image: citicup/citicup-frontend
    container_name: citicup-frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARTIFACT_NAME=citicup-frontend
        - EXPOSED_PORT=8000
    entrypoint: ["./dockerize","-wait=tcp://citicup-mysql:3306","-timeout=60s","--","./app","-profile","prod"]
    networks:
      - citicup
  # 后端, 暂时一个微服务
  citicup-admin:
    image: citicup/citicup-admin
    container_name: citicup-admin
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARTIFACT_NAME=citicup-admin
        - EXPOSED_PORT=8080
    entrypoint: ["./dockerize","-wait=tcp://citicup-mysql:3306","-timeout=60s","--","./app","-profile","prod"]
    networks:
      - citicup


networks:
  citicup:
    driver: bridge
  proxy:
    external: true
