version: '2'
# 开发环境下的docker-compose
services:
  citicup-mysql:
    image: 'mysql:5.7.21'
    container_name: citicup-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=citicup
    volumes: # 设置映射目录
      - ./mysqldb/data:/data/db
      - ./mysqldb/backup:/data/backup
    ports:
      - '33006:3306'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']


