basePath: '{{.BasePath}}'
definitions:
  model.Companies:
    items:
      properties:
        companyName:
          type: string
        id:
          type: integer
      type: object
    type: array
  model.Company:
    properties:
      companyName:
        type: string
      id:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
  description: The Official Api Document For the Citicup
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Citicup Api
  version: "1.0"
paths:
  /api/companies:
    get:
      consumes:
      - application/json
      description: Get All Companies.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Companies'
            type: object
        "404":
          description: Resource not found
          schema:
            type: string
        "500":
          description: Internal Error
          schema:
            type: string
      summary: 获取所有公司
      tags:
      - Company
    post:
      consumes:
      - application/json
      description: Delete company
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Company'
            type: object
        "404":
          description: Resource not found
          schema:
            type: string
        "500":
          description: Internal Error
          schema:
            type: string
      summary: 添加新的公司
      tags:
      - Company
    put:
      consumes:
      - application/json
      description: Update the company information
      produces:
      - application/json
      responses:
        "200": {}
        "404":
          description: Resource not found
          schema:
            type: string
        "500":
          description: Internal Error
          schema:
            type: string
      summary: 更新公司信息
      tags:
      - Company
  /api/companies/{id}:
    delete:
      consumes:
      - application/json
      description: Delete company
      responses:
        "200": {}
        "404":
          description: Resource not found
          schema:
            type: string
        "500":
          description: Internal Error
          schema:
            type: string
      summary: 删除指定公司信息
      tags:
      - Company
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Company'
            type: object
        "404":
          description: Resource not found
          schema:
            type: string
        "500":
          description: Internal Error
          schema:
            type: string
      summary: 根据Id获取公司信息
      tags:
      - Company
swagger: "2.0"
