version: "3"

services:
  mysql:
    image: 'mysql:5.7.21'
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=citicup
    volumes: # 设置映射目录
      - ./mysqldb/data:/data/db
      - ./mysqldb/backup:/data/backup
    ports:
      - "33006:3306"