package web

import (
	_ "citicup-admin/docs" // docs is generated by Swag CLI, you have to import it.
	"citicup-admin/internal/config"
	"citicup-admin/internal/service"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
	"net/http"
	"strconv"
	"strings"
)

var (
	serv *service.Service
)

func New(c *config.Config, s *service.Service) (httpSrv *http.Server) {
	//gin.SetMode(gin.ReleaseMode)
	engine := gin.New()
	//engine.Use(gin.Recovery())
	routeSetUp(engine)

	httpSrv = &http.Server{
		Addr:    strings.Join([]string{":", strconv.Itoa(c.App.Port)}, ""),
		Handler: engine,
	}
	serv = s
	go func() {
		// service connections
		if err := httpSrv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			panic(err)
		}
	}()
	return
}

func routeSetUp(e *gin.Engine) {
	e.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	g := e.Group("/api")
	{
		userRouter := g.Group("/users")
		{
			userRouter.GET("", GetUserList)
		}
		companyRouter := g.Group("/companies")
		{
			companyRouter.GET("", GetCompanies)
			companyRouter.GET("/:id", GetCompanyById)
			companyRouter.POST("", NewCompany)
			companyRouter.PUT("", UpdateCompany)
			companyRouter.DELETE("/:id", DeleteCompanyById)
		}
	}
}
