server:
  port: 8080
eureka:
  instance:
    hostname: discovery-server
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
frontend: citicup-frontend
backend: citicup-admin
model: citicup-model

spring:
  application:
    name: spring-cloud-apiGateway
  cloud:
    gateway:  # 注意: 定义顺序必须是从严格到宽松. 当匹配到后便进行路由分配
      routes:
        - id: citicup-model
          uri: http://${model}:5000/
          predicates:
            - Path=/api/predict/**

        - id: citicup-backend
          uri: http://${backend}:8080/
          predicates:
            - Path=/api/**

        - id: citicup-swagger-api
          uri: http://${backend}:8080/
          predicates:
            - Path=/swagger/**

        - id: citicup-frontend
          uri: http://${frontend}:8000/
          predicates:
            - Path=/**
